call_option.go
call_option_test.go
invoke.go
invoke_test.go

Changes the retrying call to use the parent total timeout.

Remove total retry timeout option

---

client_option.go
client_option_test.go
dial.go

On Dial, if Connection is not nil, it's used in place of any user
provided gRPC settings or the default.

Add Connection ClientSetting

---

README.md
gax.go

Make clear that end users will rarely use this library directly.
Add license information and required Go version to README.
Fixes #38.

Make README more helpful

---

call_option.go
invoke.go
invoke_test.go

This contains a breaking change that should not affect end users.
The APICall signature now also accepts a CallSettings struct.

add gRPC call options

---

gax.go
path_template.go
path_template_parser.go
path_template_test.go

Reverts googleapis/gax-go#49
See: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/748
We should wait until google-cloud-go cuts a new release before redoing this.

Revert "delete path template"

---

README.md
gax.go

gax has been tagged stable (v2.0.0) more than 6 months ago.
We seem to have forgotten to update the reported version and readme :(.

document stability

---

.travis.yml

- No need to install cover tool; it is already a part of go tool itself.
- No need to install goimports; it depends on "context" and makes go1.6
fail on CI
Also @jadekler

travis: remove unnecessary scripts

---

v2/call_option.go

NewTicker(time.Duration(0)) is illegal - let's prevent it from being able to
happen.

backoff starts at 1 instead of zero

---

LICENSE
call_option.go
gax.go
header.go
invoke.go
v2/call_option.go
v2/call_option_test.go
v2/gax.go
v2/header.go
v2/header_test.go
v2/invoke.go
v2/invoke_test.go

Also adds missing licenses to header.go, v2/header.go, v2/header_test.go.
This reverts commit 5d9b035a0f099e127807649b24dd5922f679670d.

Revert "update licenses to use apache with google LLC (#63)"

---

internal/kokoro/test.sh

Taking a stab in the dark as to where the repository is located, based on
https://github.com/googleapis/google-cloud-java/blob/940999d7a50b1d006b5869c1bcd1eea7aaec4c71/.kokoro/common.cfg#L12

fix kokoro path

---

go.mod
v2/go.mod

Relevant context: https://github.com/google/go-genproto/pull/164
Also removes unnecessary (and troublesome) go1.12 line in v2/.

gax: update protobuf-golang plugin to 1.3.1

---

internal/kokoro/test.sh

As of Oct 1, 2019 GCP is no longer supporting Go 1.9 and 1.10.
Cleaning up build scripts to support this.

internal: drop support for 1.9 and 1.10

---

v2/call_option.go
v2/example_test.go
v2/gax.go
v2/invoke.go

- Use "retry period" instead of "retry envelope", since period is a well known
term describing one complete cycle.
- Add note that Backoff does not have a MaxNumRetries/RetryDeadline, which is a
common question.
- Add example of using Backoff with an HTTP client, since the OnCodes example is
grpc-specific.

better docs around Backoff

---

v2/example_test.go

It was added in Go 1.13.
Fixes #99.

v2: don't use http.NewRequestWithContext

---

.github/CODEOWNERS

Add `actools-go` to CODEOWNERS.

chore: add actools-go to CODEOWNERS

---

v2/call_option.go
v2/call_option_test.go
v2/example_test.go

This introduces a new method of creating a `Retryer` designed to evaluate Go `error`s for retry rather than a specific API Call Status type (e.g. grpc `Status`). 
`OnErrorFunc` accepts `shouldRetry func(err error) bool`, which is used to determine if an error given to the `Retryer.Retry` implementation should be retried or not. End users supply `shouldRetry` and have maximum flexibility in what they are testing the `error` for.
For GAPICs, this would mean we could generate default retryers for HTTP Status Codes wrapping error HTTP response in `googleapi.Error` and using `OnErrorFunc` with a `shouldRetry` comparing the `googleapi.Error.Code` to a set of desired codes. 
For some Veneers, it will enable retry of some transient errors wrapped in the normally not-retried `Unknown` status code. …

feat: add OnErrorFunc Retryer

---

v2/go.mod
v2/go.sum

#121 messed up the `genproto` dep pseudo-version

chore: fix go.mod pseudo-version

---

v2/call_option.go
v2/call_option_test.go
v2/example_test.go

This adds the `OnHTTPCodes` `CallOption` for configuring a `Retryer` to retry  a set of HTTP status codes present in an `error` of type `googleapi.Error`.

feat(v2): add OnHTTPCodes CallOption

---

v2/apierror/apierror.go

Now that `v2` is on `go 1.15` we can use `errors`.

fix(v2/apierror): use errors.As in FromError

---

go.mod
v2/go.mod

Updating the 'go' directive to 'go 1.17' will enable module graph
pruning (https://go.dev/ref/mod#graph-pruning), which will allow users
who depend on these modules to prune out irrelevant transitive
dependencies.
Note that updating to 'go 1.17' *will not* break existing users on
versions older than 1.17. (The 'go' version is the version required
for full fidelity — in this case, graph pruning — but older versions
of the Go toolchain will continue to make a best-effort attempt to
compile packages and will not report an error if that attempt
succeeds, as it will in this case.)

chore(all): update to 'go 1.17' to enable module graph pruning

---

v2/proto_json_stream_test.go

It doesn't appear that the specific API used in this test is important. Switching to use a non-cloud API in this test allows this library to avoid use of cloud APIs, which in the future could enable dropping cloud.google.com/go out of the dependency tree entirely
Related to https://github.com/kubernetes/kubernetes/issues/113366
cc @codyoss @noahdietz

chore(v2): switch ProtoJSONStream test to use non-cloud API

---

.github/renovate.json

chore: increase renovate maximum supported Go version to 1.19

---

v2/apierror/apierror.go
v2/apierror/apierror_test.go
v2/apierror/testdata/debug_info.golden
v2/apierror/testdata/help.golden
v2/apierror/testdata/http_err.golden
v2/apierror/testdata/localized_message.golden
v2/apierror/testdata/resource_info.golden
v2/apierror/testdata/unknown.golden

* return Unknown status when googleapi.Error because gRPC treats nil as OK
closes: #254

fix(v2/apierror): return Unknown GRPCStatus when err source is HTTP

---

v2/header.go
v2/header_test.go

Adds `GoVersion` package variable that is populated on `init` with an internal `goVersion` method. This `goVersion` method is a copy of the `versionGo` method, which was generated in every GAPIC. Once this is released, we can remove `versionGo` from every GAPIC while migrating all to use this `GoVersion` (https://github.com/googleapis/gapic-generator-go/issues/1299)
Note: The `goVersion` implementation was copied directly from the generated `versionGo` except for one caveat. When the runtime version is a prerelease and already contains a dash `-` separator, we don't need to include another one when concatenating the semver and prerelease strings.

feat(v2): add GoVersion package variable

---

v2/header.go
v2/header_test.go

Some development Go runtime versions do not use the `devel +` prefix that `goVersion` already accounted for. To handle this, if it is non-devel (as already defined) and has spaces, we trim everything after the first space, which should be the Go version we want to report.

fix(v2): handle space in non-devel go version

---

v2/callctx/callctx.go
v2/callctx/callctx_example_test.go
v2/callctx/callctx_test.go

Add a new callctx package to gax to facilitate adding and retrieving values from context.Context that our libraries can use to share information throughout the call stack. The first addition to this package will be two APIs to allow users to set RPC headers that will be added to API requests our clients make.
A follow up PR will be made to add using these after these changes are merged with #290.

feat(v2/callctx): add new callctx package

---

v2/header.go
v2/header_test.go

replaces: #286
refs: https://github.com/googleapis/gapic-generator-go/issues/1300
refs: https://github.com/googleapis/gapic-generator-go/issues/1301
This PR moves the generated `insertMetadata` and `buildHeaders` functions to new, relocated gax header functions.

feat(v2): add BuildHeaders and InsertMetadata to header 

---

v2/callctx/callctx.go
v2/callctx/callctx_example_test.go
v2/header.go

Adds `XGoogFieldMask` constant for use with `SetHeaders` to supply the Google API system parameter.
Include documentation "redirect" to `callctx` for `BuildHeaders` and other internal header related helpers in the top level package.
Add example snippets for `XGoogFieldMask`.
Fixes #320 - we will only do this constant for now.

fix: add XGoogFieldMask constant

---

v2/call_option.go

docs(v2): Fix Backoff doc to accurately explain Multiplier
