- api_callable.go
- api_callable_test.go
Allows the user to pass a function which takes a modified context based
on the provided call options.
The benefit is avoiding runtime casting in the generated surface.
> Change CreateAPICall to Invoke

- call_option.go
- call_option_test.go
- client_option.go
- client_option_test.go
- dial.go
- invoke.go
Makes settings structs public.
> Update to reflect codegen

- path_template.go
- path_template_parser.go
- path_template_test.go
Also added a small test.
Resolves #11
> Replace the existing path template parser with a recursive descent parser.

- invoke_test.go
- path_template.go
- path_template_test.go
> Rename instantiate to render

- client_option.go
- client_option_test.go
- dial.go
> add WithInsecure client option

- invoke.go
- invoke_test.go
Previously, if the context finishes early, timeSleeper returns the
context's error and ignore the timer.
This has no correctness problem, but the GC will only be able to collect
the timer after the timer expires.
This commit explicitly stop the timer, so that the GC can claim it
immediately.
> Explicitly stop timer if context finishes early

- call_option.go
- call_option_test.go
> use status.Code instead of grpc.Code

- README.md
> Add GoDoc badge and go get instructions

- v2/invoke.go
In this CL, we check errors for a permanent connection problem.
Specifically if certificates are misconfigured, or ca-certificates are missing,
we expect not to be able to establish a connection in a reasonable amount of
time and instead bail out and return the error to the user to fix.
Fixes https://github.com/googleapis/google-cloud-go/issues/1234
_Note:_ For some clients (those using the "pool resolver"), this change won't have an affect until the next version of grpc-go in which https://github.com/grpc/grpc-go/pull/2508 is included. The next release should happen mid-January.
_Note:_ This PR will be tagged v2.0.3.
> never retry permanent connection errors

- RELEASING.md
- v2/gax.go
This commit will be tagged v2.0.3.
> fix version in v2/gax.go, add RELEASING.md

- README.md
> update README install instructions for v2

- v2/gax.go
This commit will be tagged v2.1.1.
Fixes: #130
> fix: correct version string

- v2/CHANGES.md
> chore(v2): bump release-please processing

- .github/release-please.yml
Tell release-please where default files are located.
Fixes: #206
> chore: fixup for release-please

- v2/go.mod
- v2/go.sum
Fixes: https://github.com/googleapis/gax-go/issues/217
> fix(v2): resolve bad genproto pseudoversion in go.mod

- internal/kokoro/vet.sh
> chore(v2): add go.mod check to vet.sh

- internal/kokoro/vet.sh
> chore(all): update vet.sh to go runtime 1.20

- v2/example_test.go
> test: add Invoke examples

- v2/go.mod
- v2/go.sum
- v2/proto_json_stream_test.go
> fix(v2): drop cloud lro test dep

- go.work.sum
Running `go test ./...` updated my go.work.sum.
> chore: updated go.work.sum
